[build]
target = "x86_64-unknown-linux-gnu"
rustc-wrapper = "/home/llouice/.cargo/bin/sccache"

[target.x86_64-unknown-linux-gnu]
# linker = "/usr/bin/clang"
# # rustflags = ["-Clink-arg=-fuse-ld=lld", "-Ctarget-cpu=native", "-Zshare-generics=y"]
# # for mold don't use lld
# # rustflags = ["-Clink-arg=-fuse-ld=/usr/bin/mold", "-Ctarget-cpu=native", "-Zshare-generics=y"]
# rustflags = ["-Ctarget-cpu=native", "-Zshare-generics=y"]
rustflags = []