extend = "../Makefile.toml"


[tasks.fr.env]
RUST_LOG = "INFO"
RUST_BACKTRACE = "1"

CARGO_INCREMENT = 0
RUSTC_WRAPPER = '${SCCACHE}'

[tasks.node]
run_task = [{ name = "d3", fork=true }, { name = "swc", fork=true }
]


[tasks.ex]
script = "npx spack && node dist_spack/build.js"


[tasks.d3]
script = "npm i --save @types/d3"

[tasks.swc]
script = "npm i --save-dev @swc/cli @swc/core"


[tasks.tsw]
description = "watch check ts file"
command = "tsc"
args = ["-w", "--pretty", "--skipLibCheck", "--noEmit", "${@}"]


[tasks.parcel]
run_task = { name = ["parcel-watch", "parcel-run"], fork = true }

[tasks.parcel-run]
command = "npx"
args = ["parcel", "-p", "9091", "src/index.html"]


[tasks.parcel-watch]
# command = "npx"
# args = ["parcel", "watch", "src/index.html", "&"]
script = "npx parcel watch src/index.html &"