[package]
name = "platform"
version = "0.1.0"
authors = ["llouice <g13920228592@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tch = "0.3.0"
anyhow = "1.0.36"
rio_api = "0.5.0"
rio_turtle = "0.5.0"
serde = { version="1.0.118", features=["derive"] }
serde_json = "1.0.60"
