[config]
default_to_workspace = false


[tasks.run]
command = "cargo"
args = ["run", "--", "--bs_trn", "5", "--bs_dev", "10", "-e", "10", "-I", "1", "--lr", "0.01"]


[tasks.first]
command = "cargo"
args = ["run", "--release", "--", "--bs_trn", "400", "--bs_dev", "4000", "-e", "5000", "-I", "50", "--lr", "0.0003", "--ex", "first", "${@}"]


[tasks.second]
command = "cargo"
args = ["run", "--release", "--", "--bs_trn", "1000", "--bs_dev", "4000", "-e", "1000", "-I", "5", "--lr", "0.001", "--ex", "second", "-R", "rank_11862.63_loss_0.23124349_epoch_20_step_860.data-00000-of-00001"]


[tasks.third]
command = "cargo"
args = ["run", "--release", "--", "--bs_trn", "1000", "--bs_dev", "4000", "-e", "1000", "-I", "200", "--lr", "0.001", "--ex", "third", "-R", "rank_11862.63_loss_0.23124349_epoch_20_step_860.data-00000-of-00001"]


[tasks.dbg]
command = "cargo"
args = ["run", "--release", "--", "--bs_trn", "300", "--bs_dev", "4000", "-e", "10", "-I", "3", "--lr", "0.01", "--steps", "100", "--ex", "debug", "-R", "rank_11641.3_loss_0.2790304_epoch_6_step_599.data-00000-of-00001", "${@}"]


[tasks.clean]
run_task = { name = ["clean_logs", "clean_ckpt"], fork = true, parallel = true }


[tasks.clean_ckpt]
command = "rm"
args = ["-f", "checkpoints/*"]


[tasks.clean_logs]
command = "rm"
args = ["-f", "logs/first/*"]