default:
    @just --list

record-full:
    cargo run --example graph -- --record --masked_label

record:
    cargo run --example graph -- --record --masked_label --suffix _dis --cat SYMPTOM_RELATE_DISEASE

size:
    cargo run --example graph -- --size --suffix _dis --cat SYMPTOM_RELATE_DISEASE
