extend = "../Makefile.toml"

[tasks.r.env]
RUST_LOG = "DEBUG"
RUST_BACKTRACE = "1"

CARGO_INCREMENT = 0
RUSTC_WRAPPER = '${SCCACHE}'

[tasks.ck]
extend = "sc"
command = "mold"
args = ['-run', 'cargo', 'check']

[tasks.watch]
extend = "sc"
command = "mold"
args = ['-run', 'cargo', 'watch']


[tasks.t]
extend = "sc"
command = "mold"
args = ['-run', 'cargo', 'test', '--lib', '--', 'nocapture']
#args = ['-run', 'cargo', 'test', '--', 'nocapture']
