extend = "../Makefile.toml"

[tasks.rev]
command = "cargo"
args = ["run", "--example", "graph", "--", "--add_rev", "--suffix", "_dis"]


[tasks.split]
command = "cargo"
args = ["run", "--example", "graph", "--", "-f", "graph_dis.txt", "--suffix", "_dis", "--split", "--cat", "SYMPTOM_RELATE_DISEASE"]


[tasks.size]
command = "cargo"
args = ["run", "--example", "graph", "--", "--size", "--suffix", "_dis", "--cat", "SYMPTOM_RELATE_DISEASE"]

[tasks.record]
command = "cargo"
args = ["run", "--example", "graph", "--", "--record", "--cat", "SYMPTOM_RELATE_DISEASE", "--suffix", "_dis"]


[tasks."e.g."]
extend = "mc"
args = ["--run", "cargo", "run", "--example", "${@}"]


# section bin
[tasks.bin]
extend = "mc"
args = ["--run", "cargo", "run", "--bin", "${@}"]

[tasks.bin.env]
RUST_LOG = "debug"


[tasks.r.env]
RUST_LOG = "DEBUG"
RUST_BACKTRACE = "1"

CARGO_INCREMENT = 0
RUSTC_WRAPPER = '${SCCACHE}'

[tasks.ck]
extend = "sc"
command = "mold"
args = ['--run', 'cargo', 'check']

[tasks.watch]
extend = "sc"
command = "mold"
args = ['--run', 'cargo', 'watch']


[tasks.t]
extend = "sc"
command = "mold"
args = ['--run', 'cargo', 'test', '--lib', '--', 'nocapture']
#args = ['--run', 'cargo', 'test', '--', 'nocapture']
