LOCAL_IP := "10.210.67.206"
LOCAL_DIR := "/run/media/llouice/LLouice/dev/Rust/my/doing/Do/platform/AdaptiveE/py"




conve-dis: fetch_train clean-conve-dis
    python train.py --ex conve-dis  --suffix _dis --model_name ConvE --visible_device_list 0 --batch_size_trn 400 --batch_size_dev 4000 -e 5000 -I 50 --lr 0.001 --use_pretrained


clean-conve-dis:
    rm -rf logs/conve-dis


conve: fetch_train clean-conve
    python train.py --model_name ConvE --visible_device_list 2 --batch_size_trn 400 --batch_size_dev 4000 -e 5000 -I 50 --lr 0.001 --ex conve --use_pretrained


clean-conve:
    rm -rf logs/conve


dbg: fetch_train
    python train.py --visible_device_list 0 -e 10 --train_size 16 --val_size 16 --test_size 16 -I 1 --debug


smoke: fetch_train clean_default
    python train.py --visible_device_list 2 -e 10 --train_size 16 --val_size 16 --test_size 16 -I 1 --use_pretrained --use_transe


clean_default:
    rm -rf logs/default


fetch_train:
    scp -r llouice@{{LOCAL_IP}}:{{LOCAL_DIR}}/train.py train.py


M src target=".":
    scp -P 17877 -r $1 llouice@10.112.186.186:/home/llouice/dev/Rust/my/ada_python/$2
