LOCAL_IP := "10.210.67.206"
LOCAL_DIR := "/run/media/llouice/LLouice/dev/Rust/my/doing/Do/platform/AdaptiveE/py"



alias prob := conve-dis-prob_loss
alias iprob := conve-dis-prob_loss-dbg
alias dp := conve-no_dropout
alias idp := conve-no_dropout-dbg
alias dpr := conve-no_dropout-reg
alias dprm := conve-no_dropout-reg-masked
alias idprm := conve-no_dropout-reg-masked-dbg
alias bloss := conve-no_dropout-reg-masked-B_loss
alias ibloss := conve-no_dropout-reg-masked-B_loss-dbg
alias gce := conve-no_dropout-reg-masked-GCELoss
alias gce2 := conve-no_dropout-reg-GCELoss
alias gce3 := conve-no_dropout-reg-GCELoss_q1
alias sce := conve-no_dropout-reg-SCELoss
alias sce2 := conve-no_dropout-reg-SCELoss_a0_1b6
alias sce3 := conve-no_dropout-reg-SCELoss_a0_1b10-wd1e2
alias sce4 := conve-no_dropout-reg-SCELoss_a6_b2_5-wd1e2
alias sce5 := conve-no_dropout-reg-SCELoss_a0_1_b6-wd1e2
alias sce6 := conve-no_dropout-reg-SCELoss_a2_4_b1-wd1e2
alias sce7 := conve-no_dropout-reg-SCELoss_a0_1_b15-wd1e2
alias sce8 := conve-no_dropout-reg-SCELoss_a0_1_b20-wd1e2
alias sce9 := conve-no_dropout-reg-SCELoss_a0_1_b30-wd1e2
alias sce10 := conve-last_dropout-reg-SCELoss_a0_1_b30-wd1e2
alias adae2 := AdaE2-nodp-reg-SCELoss_a0_1_b30-wd1e2
alias iadae2 := AdaE2-nodp-reg-SCELoss_a0_1_b30-wd1e2-dbg
alias adae3 := AdaE2-nodp-reg-SCELoss_a0_1_b30-wd1e2-resnet
alias adae4 := AdaE2-nodp-reg-SCELoss_a0_1_b10-wd1e2-resnet
alias adae5 := AdaE2-nodp-reg-SCELoss_a6_b1-wd1e2-resnet
alias adae6 := AdaE2-nodp-reg-SCELoss_a10_b1-wd1e2-resnet
alias adae7 := AdaE2-nodp-reg-SCELoss_a20_b1-wd1e2-resnet


AdaE2-nodp-reg-SCELoss_a20_b1-wd1e2-resnet: fetch_train clean-AdaE2-nodp-reg-SCELoss_a20_b1-wd1e2-resnet
    python train.py --wd 0.01 --alpha 6.0 --beta 1.0 --no_masked_label --ex AdaE2-nodp-reg-SCELoss_a20_b1-wd1e2-resnet  --suffix _dis --model_name AdaE2 --visible_device_list 3 --batch_size_trn 400 --batch_size_dev 4000 -e 200 -I 50 --lr 0.001 --use_pretrained


clean-AdaE2-nodp-reg-SCELoss_a20_b1-wd1e2-resnet:
    rm -rf logs/AdaE2-nodp-reg-SCELoss_a20_b1-wd1e2-resnet


AdaE2-nodp-reg-SCELoss_a10_b1-wd1e2-resnet: fetch_train clean-AdaE2-nodp-reg-SCELoss_a10_b1-wd1e2-resnet
    python train.py --wd 0.01 --alpha 6.0 --beta 1.0 --no_masked_label --ex AdaE2-nodp-reg-SCELoss_a10_b1-wd1e2-resnet  --suffix _dis --model_name AdaE2 --visible_device_list 3 --batch_size_trn 400 --batch_size_dev 4000 -e 200 -I 50 --lr 0.001 --use_pretrained


clean-AdaE2-nodp-reg-SCELoss_a10_b1-wd1e2-resnet:
    rm -rf logs/AdaE2-nodp-reg-SCELoss_a10_b1-wd1e2-resnet


AdaE2-nodp-reg-SCELoss_a6_b1-wd1e2-resnet: fetch_train clean-AdaE2-nodp-reg-SCELoss_a6_b1-wd1e2-resnet
    python train.py --wd 0.01 --alpha 6.0 --beta 1.0 --no_masked_label --ex AdaE2-nodp-reg-SCELoss_a6_b1-wd1e2-resnet  --suffix _dis --model_name AdaE2 --visible_device_list 3 --batch_size_trn 400 --batch_size_dev 4000 -e 200 -I 50 --lr 0.001 --use_pretrained


clean-AdaE2-nodp-reg-SCELoss_a6_b1-wd1e2-resnet:
    rm -rf logs/AdaE2-nodp-reg-SCELoss_a6_b1-wd1e2-resnet


AdaE2-nodp-reg-SCELoss_a0_1_b10-wd1e2-resnet: fetch_train clean-AdaE2-nodp-reg-SCELoss_a0_1_b10-wd1e2-resnet
    python train.py --wd 0.01 --alpha 0.1 --beta 10.0 --no_masked_label --ex AdaE2-nodp-reg-SCELoss_a0_1_b10-wd1e2-resnet  --suffix _dis --model_name AdaE2 --visible_device_list 3 --batch_size_trn 400 --batch_size_dev 4000 -e 200 -I 50 --lr 0.001 --use_pretrained


clean-AdaE2-nodp-reg-SCELoss_a0_1_b10-wd1e2-resnet:
    rm -rf logs/AdaE2-nodp-reg-SCELoss_a0_1_b10-wd1e2-resnet


AdaE2-nodp-reg-SCELoss_a0_1_b30-wd1e2-resnet: fetch_train clean-AdaE2-nodp-reg-SCELoss_a0_1_b30-wd1e2-resnet
    python train.py --wd 0.01 --alpha 0.1 --beta 30.0 --no_masked_label --ex AdaE2-nodp-reg-SCELoss_a0_1_b30-wd1e2-resnet  --suffix _dis --model_name AdaE2 --visible_device_list 3 --batch_size_trn 400 --batch_size_dev 4000 -e 200 -I 50 --lr 0.001 --use_pretrained


clean-AdaE2-nodp-reg-SCELoss_a0_1_b30-wd1e2-resnet:
    rm -rf logs/AdaE2-nodp-reg-SCELoss_a0_1_b30-wd1e2-resnet


AdaE2-nodp-reg-SCELoss_a0_1_b30-wd1e2-dbg: fetch_train clean-AdaE2-nodp-reg-SCELoss_a0_1_b30-wd1e2-dbg
    python -m pdb train.py --wd 0.01 --alpha 0.1 --beta 30.0 --no_masked_label --ex AdaE2-nodp-reg-SCELoss_a0_1_b30-wd1e2-dbg  --suffix _dis --model_name AdaE2 --visible_device_list 1 --batch_size_trn 400 --batch_size_dev 4000 -e 200 -I 50 --lr 0.001 --use_pretrained


clean-AdaE2-nodp-reg-SCELoss_a0_1_b30-wd1e2-dbg:
    rm -rf logs/AdaE2-nodp-reg-SCELoss_a0_1_b30-wd1e2-dbg


AdaE2-nodp-reg-SCELoss_a0_1_b30-wd1e2: fetch_train clean-AdaE2-nodp-reg-SCELoss_a0_1_b30-wd1e2
    python train.py --wd 0.01 --alpha 0.1 --beta 30.0 --no_masked_label --ex AdaE2-nodp-reg-SCELoss_a0_1_b30-wd1e2  --suffix _dis --model_name AdaE2 --visible_device_list 3 --batch_size_trn 400 --batch_size_dev 4000 -e 200 -I 50 --lr 0.001 --use_pretrained


clean-AdaE2-nodp-reg-SCELoss_a0_1_b30-wd1e2:
    rm -rf logs/AdaE2-nodp-reg-SCELoss_a0_1_b30-wd1e2


conve-last_dropout-reg-SCELoss_a0_1_b30-wd1e2: fetch_train clean-conve-last_dropout-reg-SCELoss_a0_1_b30-wd1e2
    python train.py --wd 0.01 --alpha 0.1 --beta 30.0 --no_masked_label --ex conve-last_dropout-reg-SCELoss_a0_1_b30-wd1e2  --suffix _dis --model_name ConvE --visible_device_list 1 --batch_size_trn 400 --batch_size_dev 4000 -e 200 -I 50 --lr 0.001 --use_pretrained


clean-conve-last_dropout-reg-SCELoss_a0_1_b30-wd1e2:
    rm -rf logs/conve-last_dropout-reg-SCELoss_a0_1_b30-wd1e2


conve-no_dropout-reg-SCELoss_a0_1_b30-wd1e2: fetch_train clean-conve-no_dropout-reg-SCELoss_a0_1_b30-wd1e2
    python train.py --wd 0.01 --alpha 0.1 --beta 30.0 --no_masked_label --ex conve-no_dropout-reg-SCELoss_a0_1_b30-wd1e2  --suffix _dis --model_name ConvE --visible_device_list 2 --batch_size_trn 400 --batch_size_dev 4000 -e 200 -I 50 --lr 0.001 --use_pretrained


clean-conve-no_dropout-reg-SCELoss_a0_1_b30-wd1e2:
    rm -rf logs/conve-no_dropout-reg-SCELoss_a0_1_b30-wd1e2


conve-no_dropout-reg-SCELoss_a0_1_b20-wd1e2: fetch_train clean-conve-no_dropout-reg-SCELoss_a0_1_b20-wd1e2
    python train.py --wd 0.01 --alpha 0.1 --beta 20.0 --no_masked_label --ex conve-no_dropout-reg-SCELoss_a0_1_b20-wd1e2  --suffix _dis --model_name ConvE --visible_device_list 1 --batch_size_trn 400 --batch_size_dev 4000 -e 200 -I 50 --lr 0.001 --use_pretrained


clean-conve-no_dropout-reg-SCELoss_a0_1_b20-wd1e2:
    rm -rf logs/conve-no_dropout-reg-SCELoss_a0_1_b20-wd1e2


conve-no_dropout-reg-SCELoss_a0_1_b15-wd1e2: fetch_train clean-conve-no_dropout-reg-SCELoss_a0_1_b15-wd1e2
    python train.py --wd 0.01 --alpha 0.1 --beta 15.0 --no_masked_label --ex conve-no_dropout-reg-SCELoss_a0_1_b15-wd1e2  --suffix _dis --model_name ConvE --visible_device_list 2 --batch_size_trn 400 --batch_size_dev 4000 -e 200 -I 50 --lr 0.001 --use_pretrained


clean-conve-no_dropout-reg-SCELoss_a0_1_b15-wd1e2:
    rm -rf logs/conve-no_dropout-reg-SCELoss_a0_1_b15-wd1e2


conve-no_dropout-reg-SCELoss_a2_4_b1-wd1e2: fetch_train clean-conve-no_dropout-reg-SCELoss_a2_4_b1-wd1e2
    python train.py --wd 0.01 --alpha 2.4 --beta 1.0 --no_masked_label --ex conve-no_dropout-reg-SCELoss_a2_4_b1-wd1e2  --suffix _dis --model_name ConvE --visible_device_list 1 --batch_size_trn 400 --batch_size_dev 4000 -e 300 -I 50 --lr 0.001 --use_pretrained


clean-conve-no_dropout-reg-SCELoss_a2_4_b1-wd1e2:
    rm -rf logs/conve-no_dropout-reg-SCELoss_a2_4_b1-wd1e2


conve-no_dropout-reg-SCELoss_a0_1_b6-wd1e2: fetch_train clean-conve-no_dropout-reg-SCELoss_a0_1_b6-wd1e2
    python train.py --wd 0.01 --alpha 0.1 --beta 6.0 --no_masked_label --ex conve-no_dropout-reg-SCELoss_a0_1_b6-wd1e2  --suffix _dis --model_name ConvE --visible_device_list 2 --batch_size_trn 400 --batch_size_dev 4000 -e 300 -I 50 --lr 0.001 --use_pretrained


clean-conve-no_dropout-reg-SCELoss_a0_1_b6-wd1e2:
    rm -rf logs/conve-no_dropout-reg-SCELoss_a0_1_b6-wd1e2


conve-no_dropout-reg-SCELoss_a6_b2_5-wd1e2: fetch_train clean-conve-no_dropout-reg-SCELoss_a6_b2_5-wd1e2
    python train.py --wd 0.01 --alpha 6.0 --beta 1.0 --no_masked_label --ex conve-no_dropout-reg-SCELoss_a6_b2_5-wd1e2  --suffix _dis --model_name ConvE --visible_device_list 1 --batch_size_trn 400 --batch_size_dev 4000 -e 300 -I 50 --lr 0.001 --use_pretrained


clean-conve-no_dropout-reg-SCELoss_a6_b2_5-wd1e2:
    rm -rf logs/conve-no_dropout-reg-SCELoss_a6_b2_5-wd1e2


conve-no_dropout-reg-SCELoss_a0_1b10-wd1e2: fetch_train clean-conve-no_dropout-reg-SCELoss_a0_1b10-wd1e2
    python train.py --wd 0.01 --alpha 0.1 --beta 10.0 --no_masked_label --ex conve-no_dropout-reg-SCELoss_a0_1b10-wd1e2  --suffix _dis --model_name ConvE --visible_device_list 2 --batch_size_trn 400 --batch_size_dev 4000 -e 300 -I 50 --lr 0.001 --use_pretrained


clean-conve-no_dropout-reg-SCELoss_a0_1b10-wd1e2:
    rm -rf logs/conve-no_dropout-reg-SCELoss_a0_1b10-wd1e2


conve-no_dropout-reg-SCELoss_a0_1b6: fetch_train clean-conve-no_dropout-reg-SCELoss_a0_1b6
    python train.py --alpha 0.1 --beta 6.0 --no_masked_label --ex conve-no_dropout-reg-SCELoss_a0_1b6  --suffix _dis --model_name ConvE --visible_device_list 2 --batch_size_trn 400 --batch_size_dev 4000 -e 2000 -I 50 --lr 0.001 --use_pretrained


clean-conve-no_dropout-reg-SCELoss_a0_1b6:
    rm -rf logs/conve-no_dropout-reg-SCELoss_a0_1b6


conve-no_dropout-reg-SCELoss: fetch_train clean-conve-no_dropout-reg-SCELoss
    python train.py --no_masked_label --ex conve-no_dropout-reg-SCELoss  --suffix _dis --model_name ConvE --visible_device_list 1 --batch_size_trn 400 --batch_size_dev 4000 -e 2000 -I 50 --lr 0.001 --use_pretrained


clean-conve-no_dropout-reg-SCELoss:
    rm -rf logs/conve-no_dropout-reg-SCELoss


conve-no_dropout-reg-GCELoss_q1: fetch_train clean-conve-no_dropout-reg-GCELoss_q1
    python train.py --no_masked_label --q 1.0 --ex conve-no_dropout-reg-GCELoss_q1  --suffix _dis --model_name ConvE --visible_device_list 1 --batch_size_trn 400 --batch_size_dev 4000 -e 2000 -I 50 --lr 0.001 --use_pretrained


clean-conve-no_dropout-reg-GCELoss_q1:
    rm -rf logs/conve-no_dropout-reg-GCELoss_q1


conve-no_dropout-reg-GCELoss: fetch_train clean-conve-no_dropout-reg-GCELoss
    python train.py --no_masked_label --ex conve-no_dropout-reg-GCELoss  --suffix _dis --model_name ConvE --visible_device_list 1 --batch_size_trn 400 --batch_size_dev 4000 -e 2000 -I 50 --lr 0.001 --use_pretrained


clean-conve-no_dropout-reg-GCELoss:
    rm -rf logs/conve-no_dropout-reg-GCELoss


conve-no_dropout-reg-masked-GCELoss: fetch_train clean-conve-no_dropout-reg-masked-GCELoss
    python train.py --ex conve-no_dropout-reg-masked-GCELoss  --suffix _dis --model_name ConvE --visible_device_list 0 --batch_size_trn 400 --batch_size_dev 4000 -e 2000 -I 50 --lr 0.001 --use_pretrained


clean-conve-no_dropout-reg-masked-GCELoss:
    rm -rf logs/conve-no_dropout-reg-masked-GCELoss


conve-no_dropout-reg-masked-B_loss-dbg: fetch_train clean-conve-no_dropout-reg-masked-B_loss-dbg
    python -m pdb train.py --ex conve-no_dropout-reg-masked-B_loss-dbg  --suffix _dis --model_name ConvE --visible_device_list 0 --batch_size_trn 400 --batch_size_dev 4000 -e 2000 -I 50 --lr 0.001 --use_pretrained clean-conve-no_dropout-reg-masked-B_loss-dbg:
    rm -rf logs/conve-no_dropout-reg-masked-B_loss-dbg


clean-conve-no_dropout-reg-masked-B_loss-dbg:
    rm -rf logs/conve-no_dropout-reg-masked-B_loss-dbg


conve-no_dropout-reg-masked-B_loss: fetch_train clean-conve-no_dropout-reg-masked-B_loss
    python train.py --ex conve-no_dropout-reg-masked-B_loss  --suffix _dis --model_name ConvE --visible_device_list 0 --batch_size_trn 400 --batch_size_dev 4000 -e 2000 -I 50 --lr 0.001 --use_pretrained


clean-conve-no_dropout-reg-masked-B_loss:
    rm -rf logs/conve-no_dropout-reg-masked-B_loss


conve-no_dropout-reg-masked-dbg: fetch_train clean-conve-no_dropout-reg-masked-dbg
    python -m pdb train.py --ex conve-no_dropout-reg-masked-dbg  --suffix _dis --model_name ConvE --visible_device_list 0 --batch_size_trn 400 --batch_size_dev 4000 -e 5000 -I 50 --lr 0.001 --use_pretrained


clean-conve-no_dropout-reg-masked-dbg:
    rm -rf logs/conve-no_dropout-reg-masked-dbg


conve-no_dropout-reg-masked: fetch_train clean-conve-no_dropout-reg-masked
    python train.py --ex conve-no_dropout-reg-masked  --suffix _dis --model_name ConvE --visible_device_list 0 --batch_size_trn 400 --batch_size_dev 4000 -e 5000 -I 50 --lr 0.001 --use_pretrained


clean-conve-no_dropout-reg-masked:
    rm -rf logs/conve-no_dropout-reg-masked


conve-no_dropout-reg: fetch_train clean-conve-no_dropout-reg
    python train.py --ex conve-no_dropout-reg  --suffix _dis --model_name ConvE --visible_device_list 0 --batch_size_trn 400 --batch_size_dev 4000 -e 5000 -I 50 --lr 0.001 --use_pretrained


clean-conve-no_dropout-reg:
    rm -rf logs/conve-no_dropout-reg


conve-no_dropout-dbg: fetch_train clean-conve-no_dropout-dbg
    python -m pdb train.py --ex conve-no_dropout-dbg  --suffix _dis --model_name ConvE --visible_device_list 0 --batch_size_trn 400 --batch_size_dev 4000 -e 5000 -I 50 --lr 0.001 --use_pretrained


clean-conve-no_dropout-dbg:
    rm -rf logs/conve-no_dropout-dbg


conve-no_dropout: fetch_train clean-conve-no_dropout
    python train.py --ex conve-no_dropout  --suffix _dis --model_name ConvE --visible_device_list 0 --batch_size_trn 400 --batch_size_dev 4000 -e 5000 -I 50 --lr 0.001 --use_pretrained


clean-conve-no_dropout:
    rm -rf logs/conve-no_dropout


conve-dis-prob_loss: fetch_train clean-conve-dis-prob_loss
    python train.py --ex conve-dis-prob_loss  --suffix _dis --model_name ConvE --visible_device_list 0 --batch_size_trn 400 --batch_size_dev 4000 -e 5000 -I 50 --lr 0.001 --use_pretrained


clean-conve-dis-prob_loss:
    rm -rf logs/conve-dis-prob_loss


conve-dis-prob_loss-dbg: fetch_train clean-conve-dis-prob_loss-dbg && clean-conve-dis-prob_loss-dbg
    python -m pdb train.py --ex conve-dis-prob_loss-dbg  --suffix _dis --model_name ConvE --visible_device_list 0 --batch_size_trn 400 --batch_size_dev 4000 -e 5000 -I 50 --lr 0.001 --use_pretrained


clean-conve-dis-prob_loss-dbg:
    rm -rf logs/conve-dis-prob_loss-dbg


conve-dis: fetch_train clean-conve-dis
    python train.py --ex conve-dis  --suffix _dis --model_name ConvE --visible_device_list 0 --batch_size_trn 400 --batch_size_dev 4000 -e 5000 -I 50 --lr 0.001 --use_pretrained


clean-conve-dis:
    rm -rf logs/conve-dis


conve: fetch_train clean-conve
    python train.py --model_name ConvE --visible_device_list 2 --batch_size_trn 400 --batch_size_dev 4000 -e 5000 -I 50 --lr 0.001 --ex conve --use_pretrained


clean-conve:
    rm -rf logs/conve


dbg: fetch_train
    python train.py --visible_device_list 0 -e 10 --train_size 16 --val_size 16 --test_size 16 -I 1 --debug


smoke: fetch_train clean_default
    python train.py --visible_device_list 2 -e 10 --train_size 16 --val_size 16 --test_size 16 -I 1 --use_pretrained --use_transe


clean_default:
    rm -rf logs/default


fetch:
    scp -r llouice@{{LOCAL_IP}}:{{LOCAL_DIR}}/train.py train.py
    scp -r llouice@{{LOCAL_IP}}:{{LOCAL_DIR}}/ada.py ada.py
    scp -r llouice@{{LOCAL_IP}}:{{LOCAL_DIR}}/justfile justfile


fetch_train:
    scp -r llouice@{{LOCAL_IP}}:{{LOCAL_DIR}}/train.py train.py


M src target=".":
    scp -P 17877 -r $1 llouice@10.112.186.186:/home/llouice/dev/Rust/my/ada_python/$2
