[config]
default_to_workspace = false

[env]
LOCAL_IP = "10.210.67.206"
LOCAL_DIR = "/run/media/llouice/LLouice/dev/Rust/my/doing/Do/platform/AdaptiveE/py"



[tasks.dbg]
command = "python"
args = ['train.py', "--visible_device_list", "0", '-e', '10', '--train_size', '16', '--val_size', '16', '--test_size', '16', '-I', '1', "--debug"]
dependencies = ["fetch_train"]


[tasks.smoke]
command = "python"
args = ['train.py', "--visible_device_list", "2", '-e', '10', '--train_size', '16', '--val_size', '16', '--test_size', '16', '-I', '1', "--use_pretrained", "--use_transe"]
dependencies = ["fetch_train", "clean_default"]


[tasks.clean_default]
command = "rm"
args = ["-rf", "logs/default"]


[tasks.ismoke]
command = "python"
args = ["-m", "pdb", 'train.py', '-e', '10', '--train_size', '16', '--val_size', '16', '--test_size', '16', '-I', '1']
dependencies = ["fetch_train"]


[tasks.transe]
command = "python"
args = ["train.py", "--visible_device_list", "2", "--batch_size_trn", "400", "--batch_size_dev", "4000", "-e", "5000", "-I", "50", "--lr", "0.0003", "--ex", "transe", "${@}", "--use_pretrained", "--use_transe"]
dependencies = ["fetch_train", "clean_transe"]


[tasks.clean_transe]
command = "rm"
args = ["-rf", "logs/transe"]


[tasks.first]
command = "python"
args = ["train.py", "--visible_device_list", "3", "--batch_size_trn", "400", "--batch_size_dev", "4000", "-e", "5000", "-I", "50", "--lr", "0.0003", "--ex", "first", "${@}"]
dependencies = ["fetch_train"]


[tasks.sgd]
command = "python"
args = ["train.py", "--opt", "Sgd", "--visible_device_list", "0", "--batch_size_trn", "400", "--batch_size_dev", "4000", "-e", "5000", "-I", "50", "--lr", "0.001", "--ex", "sgd", "--ckpt_dir", "checkpoints_sgd", "${@}"]
dependencies = ["fetch_train"]


[tasks.fetch_train]
command = "scp"
args=['-r', 'llouice@${LOCAL_IP}:${LOCAL_DIR}/train.py', 'train.py']
