[config]
default_to_workspace = false

[env]
LOCAL_IP = "10.210.67.206"
LOCAL_DIR = "/run/media/llouice/LLouice/dev/Rust/my/doing/Do/platform/AdaptiveE/py"

[tasks.conve-resume]
command = "python"
args = ["train.py", "--ckpt", "rank_8811.6642578125_loss_0.19876775459958873_epoch_5400_step_588709.data-00000-of-00001", "--model_name", "ConvE", "--visible_device_list", "2", "--batch_size_trn", "400", "--batch_size_dev", "4000", "-e", "10000", "-I", "50", "--lr", "0.03", "--ex", "conve", "--use_pretrained", "${@}"]
dependencies = ["fetch_train"]


[tasks.iconve-resume]
command = "python"
args = ["-m", "pdb", "train.py", "--ckpt", "rank_8811.6642578125_loss_0.19876775459958873_epoch_5400_step_588709.data-00000-of-00001", "--model_name", "ConvE", "--visible_device_list", "2", "--batch_size_trn", "400", "--batch_size_dev", "4000", "-e", "10000", "-I", "50", "--lr", "0.03", "--ex", "conve", "--use_pretrained", "${@}"]
dependencies = ["fetch_train"]


[tasks.conve]
command = "python"
args = ["train.py", "--model_name", "ConvE", "--visible_device_list", "2", "--batch_size_trn", "400", "--batch_size_dev", "4000", "-e", "5000", "-I", "50", "--lr", "0.001", "--ex", "conve", "${@}", "--use_pretrained"]
dependencies = ["fetch_train", "clean-conve"]

[tasks.clean-conve]
command = "rm"
args = ["-rf", "logs/conve"]


[tasks.transe-no-ic-normal-lr1e-2]
command = "python"
args = ["train.py", "--visible_device_list", "2", "--batch_size_trn", "400", "--batch_size_dev", "4000", "-e", "5000", "-I", "50", "--lr", "0.01", "--ex", "transe-no-ic-normal-lr1e-2", "${@}", "--use_pretrained", "--use_transe"]
dependencies = ["fetch_train", "clean-transe-no-ic-normal-lr1e-2"]

[tasks.clean-transe-no-ic-normal-lr1e-2]
command = "rm"
args = ["-rf", "logs/transe-no-ic-normal-lr1e-2"]


[tasks.transe-no-ic-normal]
command = "python"
args = ["train.py", "--visible_device_list", "2", "--batch_size_trn", "400", "--batch_size_dev", "4000", "-e", "5000", "-I", "50", "--lr", "0.003", "--ex", "transe-no-ic-normal", "${@}", "--use_pretrained", "--use_transe"]
dependencies = ["fetch_train", "clean-transe-no-ic-normal"]

[tasks.clean-transe-no-ic-normal]
command = "rm"
args = ["-rf", "logs/transe-no-ic-normal"]


[tasks.transe-no-ic]
command = "python"
args = ["train.py", "--visible_device_list", "2", "--batch_size_trn", "400", "--batch_size_dev", "4000", "-e", "5000", "-I", "50", "--lr", "0.0003", "--ex", "transe-no-ic", "${@}", "--use_pretrained", "--use_transe"]
dependencies = ["fetch_train", "clean_transe_no_ic"]

[tasks.clean_transe_no_ic]
command = "rm"
args = ["-rf", "logs/transe-no-ic"]


[tasks.dbg]
command = "python"
args = ['train.py', "--visible_device_list", "0", '-e', '10', '--train_size', '16', '--val_size', '16', '--test_size', '16', '-I', '1', "--debug"]
dependencies = ["fetch_train"]


[tasks.smoke]
command = "python"
args = ['train.py', "--visible_device_list", "2", '-e', '10', '--train_size', '16', '--val_size', '16', '--test_size', '16', '-I', '1', "--use_pretrained", "--use_transe", "${@}"]
dependencies = ["fetch_train", "clean_default"]


[tasks.clean_default]
command = "rm"
args = ["-rf", "logs/default"]


[tasks.ismoke]
command = "python"
args = ["-m", "pdb", 'train.py', '-e', '10', '--train_size', '16', '--val_size', '16', '--test_size', '16', '-I', '1']
dependencies = ["fetch_train"]


[tasks.transe]
command = "python"
args = ["train.py", "--visible_device_list", "2", "--batch_size_trn", "400", "--batch_size_dev", "4000", "-e", "5000", "-I", "50", "--lr", "0.0003", "--ex", "transe", "${@}", "--use_pretrained", "--use_transe"]
dependencies = ["fetch_train", "clean_transe"]


[tasks.clean_transe]
command = "rm"
args = ["-rf", "logs/transe"]


[tasks.first]
command = "python"
args = ["train.py", "--visible_device_list", "3", "--batch_size_trn", "400", "--batch_size_dev", "4000", "-e", "5000", "-I", "50", "--lr", "0.0003", "--ex", "first", "${@}"]
dependencies = ["fetch_train"]


[tasks.sgd]
command = "python"
args = ["train.py", "--opt", "Sgd", "--visible_device_list", "0", "--batch_size_trn", "400", "--batch_size_dev", "4000", "-e", "5000", "-I", "50", "--lr", "0.001", "--ex", "sgd", "--ckpt_dir", "checkpoints_sgd", "${@}"]
dependencies = ["fetch_train"]


[tasks.fetch_train]
command = "scp"
args=['-r', 'llouice@${LOCAL_IP}:${LOCAL_DIR}/train.py', 'train.py']
